# Generated by Django 5.2.6 on 2025-09-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='horaentrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='horasalida',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
