# Generated by Django 5.2.6 on 2025-10-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registro_horasalida_alter_registro_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
