# Generated by Django 5.2.6 on 2025-10-30 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registro_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='estado',
            new_name='estado_finalizado',
        ),
    ]
