# Generated by Django 5.2.6 on 2025-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('horaentrada', models.DateTimeField(auto_now_add=True)),
                ('horasalida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
