# Generated by Django 5.2.6 on 2025-09-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_alter_registro_horaentrada_alter_registro_horasalida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='horasalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
